#!/bin/bash

echo "<html><head><title>Microsoft Windows</title></head>"
echo "<body bgcolor=\"#000088\" scroll=\"no\">"
echo "<font face=\"Lucida Console\" size=\"4\" color=\"white\">"
echo "<p>A problem has been detected and Windows has been shutdown to prevent damage to your computer.</p>"
echo "<p>DRIVER_IRQL_NOT_LESS_OR_EQUAL</p>"
echo "<p>If this is the first time you've seen this stop error screen, restart your computer. If this screen appears again, follow these steps:</p>"
echo "<p>Check to make sure any new hardware or software is properly installed. If this is a new installation, ask your hardware or software manufacturer for any Windows updates you might need.</p>"
echo "<p>If problems continue, disable or remove any newly installed hardware or software. Disable BIOS memory options such as caching or shadowing. If you need to use Safe Mode to remove or disable components, restart your computer, press F8 to select Advanced Startup Options, and then select Safe Mode.</p>"
echo "<p>Technical information:</p>"
echo "<p>*** STOP: 0x00D1 (0x00C,0x002,0x00,F86B5A89)</p>"
echo "<p>*** gv3.sys - Address F86B5A89 base at F86B5000, DateStamp 3dd9919eb</p>"
echo "<p>Beginning dump of physical memory</p>"
echo "<p>Physical memory dump complete.</p>"
echo "<p>Contact your system administrator or technical support group for further assistance.</p>"
echo "</font>"
echo "</body>"
echo "<script language=\"javascript\">"
echo "function noClick() {"
echo "  if ((event.button==1) || (event.button==2)) {"
echo "    alert('Error: 00101100x00100100 missing keymgr.dll');"
echo "  }"
echo "}"
echo "document.onmousedown=noClick;"
echo "</script>"
echo "</html>"
